### ISSUE TITLE
empty form "Notified users"

### ISSUE THREAD

**Issue by vklymchuk** [jbbarth/redmine_notified#5]
In the log I found these lines:

`I, [2020-07-22T16:51:34.910492 #26900]  INFO -- : [1;32mDeface: [WARNING][0m No :original defined for 'add-notified-emails-for-issue-creation', you should change its definition to include:
 :original => '5e02c9d81ca727e071bb83e5527eef6c326a9005' 

E, [2020-07-22T16:51:35.132330 #26900] ERROR -- : [1;32mDeface:[0m 'add-notified-users-in-issues-edit' matched 0 times with 'fieldset:contains("field_notes")'

E, [2020-07-22T16:51:35.151065 #26900] ERROR -- : [1;32mDeface: [ERROR][0m The original source for 'add-notified-users-in-issues-edit' has changed, this override should be reviewed to ensure it's still valid.

I, [2020-07-22T16:51:35.180394 #26900]  INFO -- :   Rendering issues/_edit.html.erb`

**Comment by nanego** [comment]
Can you please provide additional details about this issue?
What do you expect and what do you get?
On which URL?
What is your Redmine version? Which are the installed plugins?

**Comment by vklymchuk** [comment]
Sorry. 
After lots of installing\uninstalling other plugins it started work. 
There were no data in the form Notified users when I clicked link in an issue but now data exists.
I close this issue.
